### ISSUE TITLE
AutoNum keys are created as "required" in the Admin app

### ISSUE THREAD

**Issue by valhuber** [valhuber/ApiLogicServer#34]
Users should not be required to enter data for db-supplied keys.

You can edit the admin.yaml, e.g., in the sample app, edit the Id to remove required, as follows:

```
  Employee:
    attributes:
      - label: ' Last Name*'
        name: LastName
        search: true
        sort: true
      - name: OnLoanDepartmentId
      - name: WorksForDepartmentId
      - name: FirstName
      - name: Title
      - name: TitleOfCourtesy
      - name: BirthDate
      - name: HireDate
      - name: Address
      - name: City
      - name: Region
      - name: PostalCode
      - name: Country
      - name: HomePhone
      - name: Extension
      - name: Photo
      - name: Notes
      - name: ReportsTo
      - name: PhotoPath
      - name: IsCommissioned
      - name: Salary
        type: DECIMAL
      - name: Id
# not correct - remove ===>. required: true
    tab_groups:
      - direction: tomany
        fks:
          - EmployeeId
        name: EmployeeAuditList
        resource: EmployeeAudit
      - direction: tomany
        fks:
          - EmployeeId
        name: EmployeeTerritoryList
        resource: EmployeeTerritory
      - direction: tomany
        fks:
          - EmployeeId
        name: OrderList
        resource: Order
      - direction: toone
        fks:
          - OnLoanDepartmentId
        name: Department
        resource: Department
      - direction: toone
        fks:
          - WorksForDepartmentId
        name: Department1
        resource: Department
    type: Employee
    user_key: LastName
```
