### ISSUE TITLE
Logic Logging not enabled by default

### ISSUE THREAD

**Issue by valhuber** [valhuber/ApiLogicServer#66]
Will be fixed next release.

Your log file should look more like this (not addition of safrs and logic_logger):

```yaml
version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"
        format: "%(message)s"

    complex:
        format: "%(asctime)s - %(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

    file:
        class: logging.NullHandler
        level: DEBUG
        formatter: simple

root:
  level: INFO
  handlers: [console]

loggers:

    api.expose_api_models:   
    #        level: DEBUG
        handlers: [console]
        propagate: no

    logic_logger:
        level: DEBUG
        handlers: [console]
        propagate: no

    safrs:
        level: DEBUG
        handlers: [console]
        propagate: no

    api.customize_api:   
    #        level: DEBUG
        handlers: [console]
        propagate: no

    database.customize_models:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    logic.declare_logic:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    security.declare_security:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    security.system.authentication:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    security.system.authorization:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    ui.admin.admin_loader:   
#        level: DEBUG
        handlers: [console]
        propagate: no
```
